### ISSUE TITLE
make gnutls problem

### ISSUE THREAD

**Issue by wuyougongzi** [awwit/httpserver#2]
hi, I am interested in this project,  I want to learn  from that. so I clone piece. I excute make command. It prints gnutls file can not find.
then I use apt-get to install gnutls. like this "sudo apt-get install gnutls-bin".  But it still prints  gnutls function undefined reference, like these: "  'gnutls_record_recv' Undefined reference" , " 'gnutls_bye' Undefined reference "  and so on.
I use ubuntu 16.04. ， Have you ever been in this situation?  So you counld help me to slove this problem.

**Comment by awwit** [comment]
Hi!

You need to install `gnutls-dev` package =)

**Comment by wuyougongzi** [comment]
I install gnutls-dev , but it still has problems, and I prints "pthread_kill undefined reference ",  "dlclose undefined reference". I search for some information. It may be the gcc make dependence. I try to solve it. but I am poor in it.

**Comment by wuyougongzi** [comment]
I install gnutls-dev , but it still has problems,   It prints "gnutls_record_recv undefined reference" .it also prints "pthread_kill undefined reference ", "dlclose undefined reference".  " sem_close undefined reference" .

**Comment by awwit** [comment]
Very strange.

The `Makefile` contains all dependencies for the linker:
https://github.com/awwit/httpserver/blob/b0f7775f58f4ca05d38c1b4b5e6040ee754f3b81/Makefile#L6

Internet search shows that these settings are required. But they already have!

Do you compile the program with the `make` command?

**Comment by wuyougongzi** [comment]
Hi 
I try it again, But it still can not make success. I look for some information, I change the makefile line 27
"$(CXX)   $(LDFLAGS) $(OBJECTS) -o $@" to 
"$(CXX)  $(OBJECTS) -o $@   $(LDFLAGS)" 
and make again. Wow!!!, it make success.

You can try it. I use ubuntu sys.

**Comment by awwit** [comment]
Great!

Your changes work for me too.
I use openSUSE.

I think for an https://github.com/awwit/httpserverapp this might suit
