### ISSUE TITLE
Error occurred when make

### ISSUE THREAD

**Issue by xiangpdu** [awwit/httpserver#6]
$ make
g++  -DPOSIX -std=c++14 -c -Wall -O2 src/socket/Socket.cpp -o build/obj/socket/Socket.o
In file included from /usr/include/x86_64-linux-gnu/bits/byteswap.h:35:0,
                 from /usr/include/endian.h:60,
                 from /usr/include/x86_64-linux-gnu/sys/types.h:216,
                 from src/socket/../system/System.h:30,
                 from src/socket/Socket.h:3,
                 from src/socket/Socket.cpp:2:
src/socket/Socket.cpp: In member function ‘bool Socket::Socket::bind(int) const’:
src/socket/Socket.cpp:108:6: error: expected id-expression before ‘(’ token
    ::htons(port),
      ^
make: *** [build/obj/socket/Socket.o] Error 1

**Comment by xiangpdu** [comment]
Can you provide the description of you solution? "fixed issue #6" show nothing of the solution.

**Comment by awwit** [comment]
Of course
https://github.com/awwit/httpserver/blob/d824fe72fe134e5abcddbb7879dd339a06142b92/src/socket/Socket.cpp#L106-L107

**Comment by xiangpdu** [comment]
If this fix should apply to all this functions like htons, htonl and so on?

**Comment by awwit** [comment]
Yes, it should help in such cases.
But only if macros are used instead of function names.
Not for all compilers and systems it is.
